import { GridHeader } from 'src/models/grid-header.interface';

export const headers: GridHeader[] = [
  {
    headerName: 'Book',
    field: 'name',
    flex: 1,
    minWidth: 200,
    resizable: true,
    sortable: true,
    unSortIcon: true,
    filter: true,
    suppressMenu: false,
    pinned: 'left',
    lockPinned: true,
  },
  {
    headerName: 'Author',
    field: 'author',
    flex: 1,
    minWidth: 200,
    resizable: true,
    sortable: false,
    unSortIcon: true,
    filter: true,
    suppressMenu: false,
  },
  {
    headerName: 'Publication date',
    field: 'publicationDate',
    flex: 1,
    minWidth: 200,
    resizable: true,
    sortable: true,
    unSortIcon: true,
    filter: false,
    suppressMenu: false,
  },
  {
    headerName: 'Genre',
    field: 'genre',
    flex: 1,
    minWidth: 200,
    resizable: true,
    sortable: true,
    unSortIcon: true,
    filter: false,
    suppressMenu: false,
    pinned: 'right',
    lockPinned: true,
  },
  {
    headerName: 'ISBN',
    field: 'ISBN',
    flex: 1,
    minWidth: 200,
    resizable: true,
    sortable: false,
    unSortIcon: true,
    filter: false,
    suppressMenu: false,
  },
  {
    headerName: 'Number of pages',
    field: 'pages',
    flex: 1,
    minWidth: 200,
    resizable: true,
    sortable: true,
    unSortIcon: true,
    filter: false,
    suppressMenu: false,
  }
];
